# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://anchal24bcs10089_db_user:TOfDRy63FhMbVZAZ@e-commercedb.foz1fkc.mongodb.net/ecommerce?appName=e-commercedb

# Server Configuration
server.port=8080

# Logging
logging.level.org.springframework=DEBUG